language: php

sudo: required

group: edge

php:
- 5.3
- 5.4
- 5.5
- 5.6
- nightly

before_script:
- which php-fpm || true
- phpenv which php-fpm || true
- for sbin_dir in $(find ~/.phpenv/versions -name sbin) ; do echo "----> ${sbin_dir}:" ; ls -ltra ${sbin_dir} ; done
