language: php

sudo: required

group: edge

php:
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6

before_script:
- which php-fpm || true
- phpenv which php-fpm || true
- php-fpm --help || true
- for sbin_dir in $(find ~/.phpenv/versions -name sbin) ; do
    echo "----> ${sbin_dir}:" ;
    ls -ltra ${sbin_dir} ;
    echo ;
  done
